version: "3.8"

services:
  db:
    image: postgres:12
    container_name: postgres_db_e_com
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    env_file:
      - env.template
    ports:
      - 5434:5432

  web:
    build: .
    container_name: free_me
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8000
    env_file:
      - env.template
    depends_on:
      - db
      - redis
    entrypoint: /entrypoint.sh

volumes:
  postgres_data: